### ISSUE TITLE
[BUG] Release 6.0.0 not compatible with TYPO3 7.6.23

### ISSUE THREAD

**Issue by stweil** [AOEpeople/crawler#262]
After upgrading to release 6.0.0, we get runtime errors (about 300 today):

    [07-Jan-2018 20:35:07 Europe/Berlin] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/typo3conf/ext/crawler/class.tx_crawler_lib.php' (include_path='/var/www/typo3_src-7.6.23/vendor/pear/pear_exception:/var/www/typo3_src-7.6.23/vendor/pear/http_request2:.:/usr/share/php') in /var/www/typo3_src-7.6.23/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 4862

File `class.tx_crawler_lib.php` was moved in commit 9ad40f6d401d877459355b2210e8eaec8b2fab3e, but is required by `typo3_src-7.6.23/typo3/sysext/indexed_search/Classes/Indexer.php`.

-- UPDATE 23.2.2018 - Tomas Mikkelsen -- 
The problem is that the indexed_search is requiring the `class.tx_crawler_lib.php` class with does not exist anymore. 

We have added:
Migrations/Code/LegacyClassesForIde.php
Migrations/Code/ClassAliasMap.php

+ Added to composer:
```
"typo3/class-alias-loader": {
            "class-alias-maps": [
                "Migrations/Code/ClassAliasMap.php"
            ]
        }
```

But all this is only working in composer mode and not in non-composer mode.  So we get an exception from the require_once in the indexed_search.

**Comment by tomasnorre** [comment]
Thanks for reporting @stweil. 

The problem is not that it's not compatible with TYPO3 7.6.23, the problem is that it's not compatible with indexed_search. 

Which version of indexed_search are you using?

**Comment by stweil** [comment]
It's `indexed_search 7.6.23`.

**Comment by tomasnorre** [comment]
True.. My bad, was sleepy... Thanks.

**Comment by tomasnorre** [comment]
@stweil Do you use composer or TER ? 

Think it's related to autoloading..

**Comment by stweil** [comment]
We are using TER.

**Comment by tomasnorre** [comment]
Thanks, then I know what the problem is.. I'll look into this.

**Comment by tomasnorre** [comment]
I've added a core-fix for this as well. 
https://review.typo3.org/#/c/55387/
https://forge.typo3.org/issues/83603?next_issue_id=83602

There will be a fix within the crawler itself as well asap.

**Comment by stucki** [comment]
@tomasnorre You are suggesting to define a `class_alias` in https://review.typo3.org/#/c/55387/. This seems to work for me, I'm not sure why it's breaking on your side. Maybe because the class_alias is only used with composer?

Anyway, one problem remains that needs to be fixed:
```
diff --git a/typo3/sysext/indexed_search/Classes/Indexer.php b/typo3/sysext/indexed_search/Classes/Indexer.php
index 172e9ec..a48f5ca 100644
--- a/typo3/sysext/indexed_search/Classes/Indexer.php
+++ b/typo3/sysext/indexed_search/Classes/Indexer.php
@@ -1928,7 +1928,12 @@ class Indexer
      */
     public function includeCrawlerClass()
     {
-        GeneralUtility::requireOnce(\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('crawler') . 'class.tx_crawler_lib.php');
+        $file = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('crawler') . 'class.tx_crawler_lib.php';
+        if (file_exists($file)) {
+            // This file was removed in exchange for autloading in EXT:crawler 6.0.
+            // It only needs to be included here for older versions.
+            GeneralUtility::requireOnce($file);
+        }
     }
 
     /********************************
```
Should we update the TYPO3_7-6 branch for TYPO3.CMS like this or do you prefer to add the file as a fallback in EXT:crawler? (This would be the easier solution if you still have problems with your tests...)

**Comment by tomasnorre** [comment]
Will you push a patch-set to the core @stucki ? I think this is a fine approach, but don't need to be for 7.6 as well.. But 8.7 and dev-master would be super. 

We want to fix it within the crawler as well though.

**Comment by stucki** [comment]
@tomasnorre Like I already wrote on Slack, I think that the fix is needed _only_ for 7.6 but not for the newer releases.

**Comment by medarob** [comment]
Not sure if it's related to this problem but I'm getting the following error when the scheduled task for the Crawler runs:

Core: Error handler (FE): PHP Warning: require_once(/var/www/typo3/typo3conf/ext/crawler/class.tx_crawler_lib.php): failed to open stream: No such file or directory in /var/www/typo3/typo3_src-7.6.23/typo3/sysext/core/Classes/Utility/GeneralUtility.php line 4862

I use Typo3 7.6.23 and The latest Crawler Extension. Any help would be appreciated.

**Comment by tomasnorre** [comment]
Hi @medarob 
Looks like it's the same issue.

**Comment by medarob** [comment]
Thank you @tomasnorre  for the answer.

Yes, I use the TER mode. Would you recommend to downgrade to the Crawler Extensions v5.2.1 as long as no fix is available?

**Comment by stweil** [comment]
There is a new TYPO3 7.6.24 available, but no hint in the release notes that this issue was fixed, so I assume it is still there. :-(

**Comment by tomasnorre** [comment]
@stweil Correct.. This will be fixed within the Crawler and not the Core as far as I know.
https://forge.typo3.org/issues/83603

**Comment by stucki** [comment]
I created a pull request for this. Does that qualify for a crawler v6.1.2 release?

**Comment by tomasnorre** [comment]
@stucki I don't see how this will solve the problem. 
https://github.com/AOEpeople/crawler/pull/275

The File been present, but empty. What will that change.. There functionality of the file will still be missing. Or ist that the reason for you reference to the hook implementation needed.

If this fixes the problem, it's for sure qualifies for a release. :)
cc: @srotsch

**Comment by stucki** [comment]
@tomasnorre It will prevent that the indexer fails at this code in TYPO3_7-6: https://github.com/TYPO3/TYPO3.CMS/blob/TYPO3_7-6/typo3/sysext/indexed_search/Classes/Indexer.php#L1924-L1932

The functionality is in fact not missing for me as long as I use composer.
However, I forgot about those users who don't use composer, so this is indeed not complete yet.
On the other hand, it would already fix 50% of the issue... :-)

**Comment by tomasnorre** [comment]
I see.. 

The non-composer usages is the biggest problem right now.. But year, will resolve the require part.. But as the entire problem is not solved, I would not qualify for a release alone.

**Comment by stucki** [comment]
Just updated the PR. This is completely untested so far. Can someone who is not using composer please check if it works?

**Comment by tomasnorre** [comment]
@stweil Can you please tell me when you get this exception ? I have non-composer version of TYPO3 running now.. 

But cannot reproduce the error.

**Comment by stweil** [comment]
Initially I was made aware of the problem by e-mails from a cron job (`/usr/bin/php /var/www/html/typo3/cli_dispatch.phpsh crawler`). Many more of those exceptions can be found in `/var/www/html/typo3conf/php_error.log`. @stucki, I now added a `/var/www/html/typo3conf/ext/crawler/class.tx_crawler_lib.php` from your PR and will report whether that fixes the exceptions.

**Comment by stweil** [comment]
The exception is fixed, but I now get new errors in `php_error.log`:

    [23-Feb-2018 11:55:03 Europe/Berlin] PHP Fatal error:  Cannot declare class tx_crawler_hooks_tsfe, because the name is already in use in /var/www/html/typo3conf/ext/crawler/Migrations/Code/LegacyClassesForIde.php on line 0

**Comment by tomasnorre** [comment]
Suggestion from: @t3easy https://twitter.com/t3easy_de/status/966992047256342529
https://docs.typo3.org/typo3cms/CoreApiReference/ExtensionArchitecture/DeclarationFile/Index.html

Can this also take care of the 
```
"typo3/class-alias-loader": {
            "class-alias-maps": [
                "Migrations/Code/ClassAliasMap.php"
            ]
        }
```

Which is added to `composer.json` ? Otherwise we are not much closer to the solution.

**Comment by medarob** [comment]
I also noticed that the file indexing (pdf, jpg,.. ) has stopped working. Maybe this is related to the error?

So, I rolled back to version 5.2.1 and now the Crawler works again but I assume that is only a temporary fix...

**Comment by tomasnorre** [comment]
@medarob Are you using composer mode ? If you are, this cannot be related.

**Comment by medarob** [comment]
Sorry, for the late reply. I use the classic mode and not the composer mode.

**Comment by tomasnorre** [comment]
Resolved with PR #275

**Comment by stucki** [comment]
@tomasnorre Thank you!

**Comment by tomasnorre** [comment]
No thank you @stucki !

**Comment by Norcoen** [comment]
I still get
```sh
[01-Oct-2020 12:40:11 Europe/Berlin] PHP Fatal error:  Cannot declare class tx_crawler_hooks_tsfe, because the name is already in use in /var/www/typo3/typo3conf/ext/crawler/Migrations/Code/LegacyClassesForIde.php on line 0
```
when running crawler scheduler Job on TYPO3 7.6 eLTS with crawler 6.7.1

**Comment by tomasnorre** [comment]
Could you please create a new issue: Then I'll be happy to take a look at it.

**Comment by Norcoen** [comment]
thanks for the fast reply @tomasnorre 

it is the same error @stweil had in 2018 a few rows above
Still better to create a new issue?

**Comment by tomasnorre** [comment]
No then it's not needed. But will have to dig into this again. 

I don't have a non-composer setup with 7.6 right now, so would need to recreate that for testing.

**Comment by Norcoen** [comment]
I'm not sure how to reproduce this error yet... my best guess is, that it is somehow related to having EXT:compatibility6 installed

**Comment by tomasnorre** [comment]
I cannot say either. But if you find a way, that would be really helpful to me.
